### PR TITLE
Database plugins

### PR DESCRIPTION
**Pull request by Fusion**
Me again!

Following your feedback, things are now much lighter: CGO dependencies are gone and, more importantly, I am now using Go's plugin mechanism so that the database backends are not compiled in GLAuth by default.

I added 3 simple targets so that either of them can be easily compiled to a dynamically loadable plugin.

You will also note that everything is self contained in its own package.

### CODE REVIEW

**Comment by Fusion** [comment]
Additionally, apologies for the Travis CI error. Not sure I understand it.
Any idea?

> package github.com/glauth/glauth/pkg/assets: cannot find package "github.com/glauth/glauth/pkg/assets" in any of:

**Comment by butonic** [comment]
The `pkg/assets/bindata.go` file is created by `make bindata`, which is used to compil the web ui in `assets` into the binary.

Could you create your PR against `dev`?

**Comment by butonic** [comment]
@Fusion I updated the base branch to dev. can you resolve the conflicts?

**Comment by Fusion** [comment]
Hi. I resolved the conflict. Note that I used GitHub's interface, due to how straightforward the resolution is. Also, I got a warning that I was committing to Master. Sorry if you were expecting a dev commit, I've always been a tad confused by GitHub's interpretation of Git.

**Comment by sonicnkt** [comment]
Is this still being worked on? Just stumbled upon glauth while looking for a simple ldap server to synchronize authentication between several services i run and it a great simple setup for my usecase.
Only thing missing for me is method for users to change their password on their own. 
Having a db backend would make this really easy to implement for using a simple webservice. 
in theory i could probably get this also working with the config file backend but i had to write my own parser and method for validation and replace the password hash, thats just way easier when working a db.

**Comment by Fusion** [comment]
@sonicnkt I think I'm going to make another attempt. I will create another pull request, make sure it's based off the dev branch; resolve conflicts due to code drift; and re-submit it.
I am not sure that the original project author is still active, though?

**Comment by Fusion** [comment]
To be clear, I have gone quite farther than originally anticipated because I needed to use GLAuth as a LDAP proxy to inject OTP when authenticating against an existing AD3 server.

I ended up supporting multiple backends, when the first one in line is the actual backend and the rest can act as middleware.

So, right now, I am using a SQLite-backed "middleware-backend" to do just that and it seems to be working well as well as passing CI.

I think I'm also going to build some binaries if you guys would like to test this.

**Comment by sonicnkt** [comment]
@Fusion would love to test a build with sqlite backend if you supply one.  What other backends are supported in your version as you are talking about multiple?

**Comment by Fusion** [comment]
> @Fusion would love to test a build with sqlite backend if you supply one. What other backends are supported in your version as you are talking about multiple?

I created a bogus release called "w1.1.3" so I guess it's a "welease." -- it is available here: https://github.com/Fusion/glauth/releases

When I talk about multiple backends, I mean our existing backends, but used together. For instance one can use the "ldap" backend to authenticate accounts against an external server we are proxying to, while also using the "sqlite" backend to add two-factor authentication based on the content of a local database.

**Comment by sonicnkt** [comment]
Just tried your "welease", couldnt get the built working on my pc because of a newer glibc dependeny tho. Because i didnt want to compile it myself i tried it using docker and a slim debian base image. This worked great.

Only tried the sqlite plugin yet tho. Next step for me would be to build a small webapp that shares the same db to allow users to authenticate and change their password, email and name. Maybe a small admin interface to easily create and configure users/groups etc.

**Comment by Fusion** [comment]
I know what you mean. A while ago I wrote a small thing to share GLauth QR codes (https://github.com/Fusion/glauth-qr-code) and, yes, there is definitely a lack of UI. Not being a Go developer (well I guess I'm becoming one) I played with Martini the other day and the results were promising. I noticed that opinions on that framework are pretty mixed though.

**Comment by Fusion** [comment]
So, this is becoming a quite the conundrum: I have been adding more feature to my cloned repo and now I am in a position where I will have to maintain that as well ;) 
I really do not mean to create a fork of glauth, especially considering my limited mastery of the Go language.

@benyanke @butonic Any word on the future of glauth?

**Pull request merged**
