### PR TITLE
Add support for including groups in groups

### PR DESCRIPTION
**Pull request by ryskov**

### CODE REVIEW

**Comment by benyanke** [comment]
That commit message should have said 'Ran 'go fmt' to fix failing test, but my shell removed it for some reason. anyways, that should now pass the test.

I'll check these PRs out today or tomorrow and take a deeper look. Thanks again - your contribution is greatly appreciated!

**Comment by benyanke** [comment]
Still trying to get this working on my end. Do you have an ldap query command or two for me to try?

**Comment by ryskov** [comment]
You can run the server with the updated sample-simple.cfg, where i created a new group called 'vpn'. The 'vpn' group should contain all members of superheroes aswell as it includes group 5501. You can run:

`ldapsearch -LLL -H ldap://localhost:389 -D cn=serviceuser,ou=svcaccts,dc=glauth,dc=com -w mysecret -x -bdc=glauth,dc=com \(objectClass=posixgroup\) `

To get a list of all groups, where you should see that the 'hackers' user is now also a member of the 'vpn' group, because of inclusion.

**Comment by ryskov** [comment]
Just pushed some commits to fix an issue with `getGroupDNs` would not take inclusion into consideration. 

I merged in amazon_fix_dev branch into this, so i could run the server, but i suppose that wouldnt be a problem since its already merged into your dev branch.

**Comment by woopstar** [comment]
Fixes #23

**Comment by benyanke** [comment]
I think you mean #18?

**Comment by benyanke** [comment]
Sorry for the delays, I've been quite busy. I'm hoping to potentially get this merged this weekend.

**Comment by benyanke** [comment]
Thanks for the great PR, @ryskov . Just finally got a chance to finish this up and merge it in this week, and added some integration (output snapshot) tests.

**Pull request merged**
