### PR TITLE
Allow hot-reloading config on change

### PR DESCRIPTION
**Pull request by ryskov**
This change add the root-level option 'watchconfig'. 

Enabling this option will make GLAuth watch for writes to the config-file. When a write is detected it will parse and validate the config, and finally swap out the activeConfig (which is feeded by ref into LDAP handlers etc. on startup) with the new one.

To be able to do this, i had to move around and rewrite a lot of stuff related to loading the config, so i was able to parse the new config in isolation, and only swap out the activeConfig when validated.

We need this feature to be able to have zero down-time while adding/removing new users or groups, or changing the debug/syslog-flags while running. 

The options comes with some limitations, which are also stated in the example config: It will NOT be able to reload the [ldap], [ldaps], [backend] or [api] sections as they are used when booting up the server-instances, and would require downtime to reload. A restart will be required when changing those.

### CODE REVIEW

**Comment by benyanke** [comment]
Adding [wip] since I didn't hear back. Please remove if/when it's ready to merge!

**Comment by ryskov** [comment]
I believe this is ready to merge. We have been using this on our fork for a while now with success

**Comment by benyanke** [comment]
Sounds good! Will merge in soon!

**Comment by ryskov** [comment]
Also fixes #14

**Pull request merged**
