### PR TITLE
fix: keep watch config file when changed,renamed,removed 

### PR DESCRIPTION
**Pull request by fanlix**
# config hot reload not works when edited by vim.
This is fsnotify lib & vim/editor/fs problem. Origin issue: fsnotify/fsnotify#17
maybe the reason of #132

## problem
* pure write works
  * `echo xxx > xx.cfg` 
  * `cp xx.cfg xx.cfg` works
* `vim xx.cfg`, use  `:w` to save, not works. 
  * also cause fsnotify quit.
  * set nobackup in vim, works. but we never do this.
  * sublime,....
* rm , then re-create/cp  not works 

## testcase
* enable in  `sample-simple.cfg`
  * watchconfig  = true 
* `./bin/glauth64   -c sample-simple.cfg`
* `rm sample-simple.cfg`
* `cp xxx sample-simple.cfg`
* `vim sample-simple.cfg` edit, save`:wq`

## success logs:
```
18:30:24.647495 doConfig ▶ DEBU 001 Debugging enabled
18:30:24.647539 startService ▶ DEBU 002 Web API enabled
18:30:24.647655 NewServer ▶ NOTI 003 Using config backend
18:30:24.647710 startLDAP ▶ NOTI 005 LDAP server listening on 0.0.0.0:3893
18:30:24.647691 RunAPI ▶ NOTI 004 Starting HTTP server on 0.0.0.0:5555
18:30:36.649141 func1 ▶ DEBU 006 rewatching sample-simple.cfg
18:30:36.650408 doConfig ▶ DEBU 007 Debugging enabled
18:30:36.650441 func1 ▶ NOTI 008 Config was reloaded
18:30:45.344117 func1 ▶ DEBU 009 rewatching sample-simple.cfg
18:30:45.345181 doConfig ▶ DEBU 00a Debugging enabled
18:30:45.345213 func1 ▶ NOTI 00b Config was reloaded
```

### CODE REVIEW

**Comment by Fusion** [comment]
Hi @fanlix can you change this pull request to be against the "dev" branch?
Other than that, looks good!

**Comment by fanlix** [comment]
You have already fixed most part of the bug in dev branch.
v2.0 seems a big improvement, cant wait anymore.

**Comment by fanlix** [comment]
changed code: https://github.com/glauth/glauth/commit/faed82ad44a908278c6e090c6c30f93a7f72d563
my pr should be ok with configMap. need test from @nwillems

**Comment by Fusion** [comment]
I don't mean to torture you, promise! But would you mind running your code through `gofmt`?

**Pull request merged**
