### PR TITLE
fix issue 144

### PR DESCRIPTION
**Pull request by fgma**
This just fixes https://github.com/glauth/glauth/issues/144

### CODE REVIEW

**Comment by fgma** [comment]
CI on darwin seems to be broken but not related to the changes in this PR.

**Comment by butonic** [comment]
Whohoo, cool! Now, the challenge is to make this backwards compatible. Otherwise updating to this version will break existing deployments. Or we have to increase the major version number.

**Comment by fgma** [comment]
Maybe merge it after https://github.com/glauth/glauth/pull/125

**Comment by butonic** [comment]
nah ... [v2.0.0](https://github.com/glauth/glauth/pull/125) has a few breaking changes on the api level ... might make sense to add some fallback code that allows both values and logs an error when the old one is found. it can continue working, but admins should see the error on startup, maybe with a message that says 'encountered deprecated config value, please update your config, support for ... will be dropped in future versions'.

**Comment by fgma** [comment]
I'm going to have a look into this when I have some time left.

**Comment by fgma** [comment]
@butonic Done. Please have a look.

**Comment by butonic** [comment]
Thx for your effort and sorry for letting you wait so long. Life happened.

I rebased this on the dev branch. Let's see what CI says now

**Comment by fgma** [comment]
I've fixed the build.

**Comment by Fusion** [comment]
Hi @fgma renewed apologies for the incredibly long delay!

Due to how much the code has drifted since your pull request, unfortunately, I had a create a brand new PR. Would you mind reviewing it? Thanks!

https://github.com/glauth/glauth/pull/201

**Comment by Fusion** [comment]
Closing in favor of #201 

Thanks, @fgma!

**Pull request closed without merging**
