### PR TITLE
Bulid and push multiarch docker images

### LINKED ISSUE #141: ARM (multiarch) docker image
I'd love to use this project dockerized in the raspberry.

Is this on the roadmap? Can I help?

cc @joao-p-marques

### PR DESCRIPTION
**Pull request by Yajo**
My intention here is to help you fix #141.

I have absolutely zero experience on golang, but here I'm giving you a recipe to build multiarch docker images and push them to GitHub package registry.

You probably want to push them too to docker hub, but since it seems you have an automated build there, I thought it would be good to start testing this in GitHub registry instead.

I removed bzr from the `Dockerfile` because it was breaking some builds and seemed like not necessary.

Now I see errors like this when building on many arches:

<pre>------
 &gt; [linux/386 build 7/8] RUN go get -u github.com/jteeuwen/go-bindata/... &amp;&amp; /tmp/gocode/bin/go-bindata -pkg=assets -o=pkg/assets/bindata.go assets &amp;&amp; gofmt -w pkg/assets/bindata.go:
#40 0.212 go: downloading github.com/jteeuwen/go-bindata v3.0.7+incompatible
#40 7.923 /bin/sh: /tmp/gocode/bin/go-bindata: not found
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c go get -u github.com/jteeuwen/go-bindata/... &amp;&amp; $GOPATH/bin/go-bindata -pkg=assets -o=pkg/assets/bindata.go assets &amp;&amp; gofmt -w pkg/assets/bindata.go]: buildkit-runc did not terminate successfully
</pre>

Interestingly, https://github.com/jteeuwen/go-bindata is unmaintained. I have no idea on what this problem could be, but I bet it's not unavoidable. Can we get rid of that line in the `Dockerfile`?

### CODE REVIEW

**Comment by Yajo** [comment]
Oh you probably want to see https://dev.to/arturklauser/building-multi-architecture-docker-images-with-buildx-1mii to understand what this is doing.

**Comment by Yajo** [comment]
You can see in https://github.com/Yajo/glauth/actions/runs/150358048 results of last run. I guess you have to enable external github actions in this repo to see those results linked in the PR (that's one objective of course).

**Comment by Yajo** [comment]
I just saw https://www.docker.com/blog/multi-arch-build-what-about-travis/ today. Would you like to use Github Actions, or would you prefer to stick with Travis?

**Comment by Yajo** [comment]
This is finally working!

Check the results in https://github.com/Yajo/glauth/pull/1/checks?check_run_id=869962750. You won't see github actions results here until enabled external actions at repo level, but after merge you'll see them.

**Comment by butonic** [comment]
Thx! I need to find some time to review and test this properly, but it looks promising!

**Comment by brettinternet** [comment]
I don't see ARM support in the docker tags: https://hub.docker.com/r/glauth/glauth/tags. Am I mistaken?

**Pull request merged**
