### PR TITLE
Rename the groups table to ldapgroups

### PR DESCRIPTION
**Pull request by wolsen**
The groups table name is a reserved keyword in mysql and requires that the table name be escaped with backticks in order to use the groups name. Other databases such as postgres do not support the use of the backticks in the query statements. This change renames the groups table to ldapgroups in oder to avoid this problem altogether.

This does have a dependency on the backend sql plugins to alter the schema to match the new name.

Note: I have tested this with mysql, postgres and sqlite backends. Separate PRs will be opened for each of the plugin repositories to handle the migration of the table schema.

### CODE REVIEW

**Comment by wolsen** [comment]
Note this PR has plugin changes that are in the following PRs:

- [glauth-mysql PR#2](https://github.com/glauth/glauth-mysql/pull/2)
- [glauth-sqlite PR#1](https://github.com/glauth/glauth-sqlite/pull/1)
- [glauth-postgres PR#1](https://github.com/glauth/glauth-postgres/pull/1)

**Comment by wolsen** [comment]
@Fusion would love your opinion on this one. I went the route of modifying the schema, since that solves it in the most practical sense.

**Comment by 0x0034** [comment]
hi~ , did you test ldap bind to query user? i'm using your code and give me some errors , have bad fillters. could you  give me some help, thx ervey much

**Comment by Fusion** [comment]
It does, and it's a good point. I need to figure out how to preserve backward compatibility, otherwise I will have to save this PR until we have a truly major release.

**Comment by Fusion** [comment]
Spoiler: I have recently introduce a way of handling this, called `LegacyVersion`, but it would still be nasty surprise for users who do not update their configuration file.

**Comment by 0x0034** [comment]
did you fix the groups in mysql8 is a key word?  in v2.2.1 code , i'm also can run it on mysql8

**Comment by 0x0034** [comment]
> Spoiler: I have recently introduce a way of handling this, called `LegacyVersion`, but it would still be nasty surprise for users who do not update their configuration file.

did you fix the groups is a key word in mysql8? i'm try v2.2.1 , but also can't run on mysql8

**Comment by Fusion** [comment]
I had not as I have been wondering, as explained above, how  to avoid making this a breaking change. Im on it today.

**Comment by Fusion** [comment]
@wolsen Thank you for your pull request. It is now merged and is about to be released in v2.3.0.
You do not need to do anything more as I am also updating the plugins: I modified the existing migrations mechanism to support renaming tables.

**Pull request merged**
