### PR TITLE
Construct DNs under ou=users for uniqueMember group attribute [WIP]

### PR DESCRIPTION
**Pull request by candlerb**
Before:

```
dn: ou=vpn,ou=users,dc=glauth,dc=com
...
uniqueMember: cn=hackers,ou=superheros,dc=glauth,dc=com
```

After:

```
dn: ou=vpn,ou=users,dc=glauth,dc=com
...
uniqueMember: cn=hackers,ou=superheros,ou=users,dc=glauth,dc=com
                                       ^^^^^^^^
```

------
This is a change in user visible behaviour, hence why flagged "[WIP]", but I believe it is reasonable. Prior to this, the "uniqueMember" attributes of a group did not match the "dn" attributes of the user entries that they are supposed to point to.

Relates to #181

### CODE REVIEW

**Review by zguig52 — APPROVED** [review]

**Comment by Fusion** [comment]
Sorry for this taking such a long time. I need to test all corner cases, due to how glauth simplifies such operations.

**Comment by Fusion** [comment]
BTW everything you wrote is correct, of course.
I spent a lot of time trying to not break backward compatibility. There is a price to pay for a design that was meant to be as simple as possible.
Now, I've been working towards more correctness, so of course I have to agree with your comments. Part of this was making it so that the directory could be browsed using a LDAP client.
After taking another deep dive through why some decisions were made in the past, I cannot find a justification for **not** going with your PR. It will be a breaking change so I need to be careful about versioning.

**Comment by andreasbruckmeier** [comment]
I would love to see this PR in one of the next releases :)

We use the nginx module https://github.com/kvspb/nginx-auth-ldap to realize basic authentication based on ldap.
Now we have a new use case where we need to restrict some locations based on group membership, but this fails with glauth.

Unfortunately, the plugin does not simply utilize the memberOf attribute of the user but searches for a given group which has the users dn listed in the uniqueMember attribute. And this never matches due to the additional ou=users in the user dn which is missing in the uniqueMember attribute.

**Comment by Fusion** [comment]
Gotcha. I imagine it acts this way because caching the groups information will provide a performance improvement.

**Pull request merged**
